# Generated by Django 4.1.7 on 2023-03-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0003_rename_brands_carsbrands'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventary.carsbrands'),
            preserve_default=False,
        ),
    ]
