# Generated by Django 4.1.7 on 2023-03-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0004_cars_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='brand name')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarsOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JunkCars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waiting', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='model name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.brands')),
            ],
        ),
        migrations.CreateModel(
            name='SoldCars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=10)),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.buyers')),
            ],
        ),
        migrations.DeleteModel(
            name='EntryCars',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='_model',
        ),
        migrations.AddField(
            model_name='cars',
            name='condition',
            field=models.CharField(default='Medium', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='inventary_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='title',
            field=models.FileField(null=True, upload_to='titles/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='waiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='soldcars',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars'),
        ),
        migrations.AddField(
            model_name='junkcars',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars'),
        ),
        migrations.AddField(
            model_name='carsout',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventary.cars'),
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventary.models'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventary.brands'),
        ),
        migrations.DeleteModel(
            name='CarsBrands',
        ),
    ]
