# Generated by Django 4.1.7 on 2023-03-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0005_brands_buyers_carsout_junkcars_models_soldcars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.CharField(default='2000', max_length=4),
        ),
        migrations.AlterField(
            model_name='cars',
            name='condition',
            field=models.CharField(choices=[(0, 'Good'), (1, 'Medium'), (2, 'Bad')], default='exit', max_length=2),
            preserve_default=False,
        ),
    ]
