# Generated by Django 4.1.7 on 2023-03-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0006_cars_year_alter_cars_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'GOOD'), ('MEDIUM', 'MEDIUM'), ('BAD', 'BAD')], max_length=6),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2000, max_length=4),
        ),
        migrations.AlterField(
            model_name='carsout',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars'),
        ),
    ]
